### ISSUE TITLE
@Title annotation: Split out @TitleCallback?

### ISSUE THREAD

**Issue by donquixote** [mediamonks/drupal-controller-annotations#10]
In my PR at #7. I proposed separate annotations for @Title and @TitleCallback.

The reason being: _title_arguments (and _title_context) are only useful in combination with _title_callback.
And _title and _title_callback are not meant to be used in combination.

Separate annotations would make it make it easier to use the API correctly.

**Comment by slootjes** [comment]
I'd rather solve this by validating the object itself than to implement separate annotations as I explained before. Will look into that. Also, please put this information in the documentation because for non Drupal users this is not clear by reading it.
