### ISSUE TITLE
Unnecessary restriction for module location in TemplateResolver

### ISSUE THREAD

**Issue by jeremy-tools** [mediamonks/drupal-controller-annotations#12]
I'm a Symfony developer working on a project using Drupal 8.4.x with some homebrew and imported modules located in folders with names like:

modules/custom/*
modules/override/*

Many of these modules contain templates needed for controllers that use annotations.  Unfortunately, the `@Template` annotation as it stands is triggering an error for these modules:

`
The website encountered an unexpected error. Please try again later.
`

Tracing the problem reveals that the drupal-controller-annotations bundle is hard-coded to expect all modules to live within:

modules/* (without the extra sub folder)

This is located in the format function, on line 85 in TemplateResolver:

`
return sprintf('modules/%s/templates/%s.html.twig', $module, $templateName);
`

To fix this problem in a future release, please amend as follows:

`
return sprintf('%s/templates/%s.html.twig', drupal_get_path('module', $module), $templateName);
`

This change will allow module templates to be located however they are configured.

**Comment by slootjes** [comment]
Excellent idea, will implement this.

**Comment by slootjes** [comment]
Done. You can update the module and it should work as you described.

**Comment by jeremy-tools** [comment]
Thank you!
