### ISSUE TITLE
ParamConverterInterface - Drupal or Symfony?

### ISSUE THREAD

**Issue by donquixote** [mediamonks/drupal-controller-annotations#2]
Looking for "ParamConverterInterface", I find:
- Drupal\Core\ParamConverter\ParamConverterInterface
- Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterInterface

The first one is used in "traditional" Drupal routes declared via *.routing.yml.
The second one is recommended in https://github.com/mediamonks/drupal-controller-annotations/blob/8.x-1.x/docs/2-usage.rst#paramconverter

Does this mean the existing Drupal param converters will not work with controllers registered via annotation?

**Comment by slootjes** [comment]
It's clearly mentioned in the docs that you should be using the Sensio ParameterConverterInterface. View the code to see how the Node is getting converted using this.

**Comment by donquixote** [comment]
Yes it is mentioned in the docs..

I imagine Drupal param converters can still be used via `@Route(options = {"parameters" = ..})`.
