### ISSUE TITLE
Automatically register menu links, tabs or other stuff?

### ISSUE THREAD

**Issue by donquixote** [mediamonks/drupal-controller-annotations#3]
https://www.drupal.org/docs/8/converting-drupal-7-modules-to-drupal-8/d7-to-d8-upgrade-tutorial-convert-hook_menu-and-hook

Would it be possible to add something to the annotation, to register menu links, tabs etc?

E.g. here, https://github.com/drupal/drupal/blob/b560f348bd5bfe11ab7c4784b529f0cca5277639/core/modules/dblog/dblog.links.menu.yml
most of this looks redundant.

I guess this would be a separate problem, not immediately related to this module..

**Comment by donquixote** [comment]
I'd say this can be closed as "wontfix". It belongs in a different module.

With https://github.com/mediamonks/drupal-controller-annotations/issues/4, it will become easy to set options and other modifications on the route object through custom annotations.
All of these modifications can also be done in the *.routing.yml file for routes registered in the traditional way.

These could then be read by a separate module, which can be totally separate from this one.

**Comment by slootjes** [comment]
Not sure if it answers your question but it is possible to put any requirement or option to a route by using annotations as described here: http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/routing.html

@Route("/{id}", requirements={"id" = "\d+"}, defaults={"id" = 1})
