### ISSUE TITLE
@RouteTitleCallback

### ISSUE THREAD

**Issue by donquixote** [mediamonks/drupal-controller-annotations#5]
How would we annotate a _title_callback?
```php
/**
 * @Route(..)
 */
class MyController {
  /**
   * @RouteTitleCallback(..)
   */
  function title($arg) {
    return Html::escape($arg);
  }

  /**
   * @Route(..)
   */
  function page($arg) {
    return ...;
  }
}
```

Question: How would we tell that the title callback is for the route method below?
The annotation could contain the route machine name.. but I would like to avoid this.
Maybe something like `@TitleCallbackForRouteBelow(..)`, or have this implicit?

Maybe this is better:
```php
/**
 * @Route(..)
 */
class MyController {

  function title($arg) {
    return Html::escape($arg);
  }

  /**
   * @Route(..)
   * @RouteTitleCallback("::title")
   */
  function page($arg) {
    return ...;
  }
}
```

Or "self::title" instead of "::title" ?

**Comment by slootjes** [comment]
You could put a "_title_callback" entry in the defaults section in your ``@Route`` declaration. I'll consider adding a ``@TitleCallback`` annotation but I'm not sure how much this is actually used. Also, "self" is unsupported by the annotation parser itself provided by Doctrine.

**Comment by slootjes** [comment]
This is now possible by using the ``@Title`` annotation, thanks for the suggestion of implementing something for this.
