### ISSUE TITLE
Annotated services? (off-topic, kind of)

### ISSUE THREAD

**Issue by donquixote** [mediamonks/drupal-controller-annotations#6]
This is not about this specific module, but a question to you as a person / developer.

This module is about replacing *.routing.yml definitions with annotations.
I wonder if the same could be done for services.

After a quick research I found this:
http://jmsyst.com/bundles/JMSDiExtraBundle/master/annotations

Interestingly, yched mentions this here, https://www.drupal.org/node/1863816#comment-6877622 5 years ago.

**Comment by slootjes** [comment]
I currently do not have plans to port this, assuming Drupal will eventually upgrade to Symfony 3.3+ components that should make service configuration a lot easier too.
